# Generated by Django 5.2.8 on 2025-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
